name: "Unittest"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: '**/poetry.lock'
      - name: Install poetry
        run: pip3 install poetry
      - name: build
        run: |
          poetry export --dev -f requirements.txt -o requirements.lock
          pip3 install -r requirements.lock
      - run: pytest .
